EMPTY = 0
ASTEROID = 1
EARTH = 2
ALIEN = 3
MISS = 4
CHEAT_DICTIONARY = {EMPTY: " ", ASTEROID: "*", EARTH: "E", ALIEN: "X", MISS: "-"}
NORMAL_DICTIONARY = {EMPTY: " ", ASTEROID: "*", EARTH: "E", ALIEN: " ", MISS: "-"}
